services:
  db:
    image: postgres:15-alpine
    container_name: veiculos_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: veiculos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d veiculos"]
      interval: 1s     # Checa a cada 1 segundos
      timeout: 3s      # Tempo limite de cada checagem
      retries: 5      # Tenta até 10 vezes antes de desistir

  api:
    build: .
    container_name: veiculos_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/veiculos
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: